[build.environment]
  GIT_LFS_ENABLED="true"
  NPM_FLAGS="--version" # prevent Netlify npm install

[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && npm run build"

[[redirect]]
  from = '/play/*'
  to = '/'

[[redirect]]
  from = '/menu'
  to = '/'
